const catalogDate = "2026-06-03T08:39:36.000Z";

function buildVariants(entries) {
 return entries.map((entry) => ({
  weight: entry.weight,
  mrp: entry.mrp,
  sale_price: entry.sale_price,
  price: entry.sale_price,
  stock: entry.stock,
  active: true,
 }));
}

function makeProduct(product) {
 const variants = buildVariants(product.variants);
 const primaryVariant = variants[0];
 return {
  featured: false,
  images: [product.image, "images/makhana_bowl_love.png"],
  created_at: catalogDate,
  updated_at: catalogDate,
  firestore_updated_at: catalogDate,
  ...product,
  price: primaryVariant.sale_price,
  sale_price: primaryVariant.sale_price,
  mrp: primaryVariant.mrp,
  stock: variants.reduce((total, variant) => total + Number(variant.stock || 0), 0),
  weight: primaryVariant.weight,
  variants,
  slug: product.slug || product.id,
  seo_title: product.seo_title || `${product.title} | Rein Oro`,
  meta_description: product.meta_description || product.description,
 };
}

export const defaultProducts = [
 makeProduct({
  id: "makhana_classic",
  name: "Makhana",
  category_id: "makhana",
  flavor: "Classic Salted",
  title: "Makhana Classic Salted",
  image: "images/makhana_classic.png",
  description:
   "Crunchy, light and slow roasted to perfection with a timeless classic salted seasoning.",
  benefits: [
   "Roasted, Not Fried",
   "Light & Crunchy",
   "Classic Salted",
   "Rich in Antioxidants",
   "Zero Cholesterol",
  ],
  benefits_image: "images/makhana_bowl_love.png",
  ingredients: [
   { name: "Makhana", img: "images/ingredient_makhana.png" },
   { name: "Rock Salt", img: "images/ingredient_salt.png" },
   { name: "Olive Oil", img: "images/ingredient_spices.png" },
  ],
  specs: {
   Brand: "Rein Oro",
   Flavour: "Classic Salted",
   "Net Weight": "100g, 250g, 500g",
   "Diet Type": "Vegetarian",
   "Shelf Life": "6 Months from date of packaging",
   "Country of Origin": "India",
  },
  nutrition: {
   Calories: "375 Kcal",
   Protein: "9.5g",
   "Total Carbohydrates": "71.2g",
   "Dietary Fiber": "7.8g",
   "Total Fat": "5.6g",
   "Trans Fat": "0g",
   Sodium: "210mg",
  },
  variants: [
   { weight: "100g", mrp: 349, sale_price: 250, stock: 48 },
   { weight: "250g", mrp: 699, sale_price: 549, stock: 36 },
   { weight: "500g", mrp: 1299, sale_price: 999, stock: 24 },
  ],
  featured: true,
 }),
 makeProduct({
  id: "makhana_cheese_onion",
  name: "Makhana",
  category_id: "makhana",
  flavor: "Cheese & Onion",
  title: "Makhana Cheese & Onion",
  image: "images/makhana_cheese_onion.png",
  description:
   "A savoury cheese and onion roasted makhana blend with a clean crunch and premium seasoning.",
  benefits: [
   "Roasted, Not Fried",
   "Light & Crunchy",
   "Perfectly Seasoned",
   "Rich in Antioxidants",
   "Zero Trans Fat",
  ],
  benefits_image: "images/makhana_bowl_love.png",
  ingredients: [
   { name: "Makhana", img: "images/ingredient_makhana.png" },
   { name: "Cheese Powder", img: "images/ingredient_cheese.png" },
   { name: "Onion Powder", img: "images/ingredient_onion.png" },
   { name: "Rock Salt", img: "images/ingredient_salt.png" },
   { name: "Spices & Herbs", img: "images/ingredient_spices.png" },
  ],
  specs: {
   Brand: "Rein Oro",
   Flavour: "Cheese & Onion",
   "Net Weight": "100g, 250g, 500g",
   "Diet Type": "Vegetarian",
   "Shelf Life": "6 Months from date of packaging",
   "Country of Origin": "India",
  },
  nutrition: {
   Calories: "385 Kcal",
   Protein: "9.2g",
   "Total Carbohydrates": "68.4g",
   "Dietary Fiber": "7.5g",
   "Total Fat": "7.8g",
   "Trans Fat": "0g",
   Sodium: "280mg",
  },
  variants: [
   { weight: "100g", mrp: 399, sale_price: 299, stock: 42 },
   { weight: "250g", mrp: 799, sale_price: 599, stock: 30 },
   { weight: "500g", mrp: 1499, sale_price: 1099, stock: 18 },
  ],
  featured: true,
 }),
 makeProduct({
  id: "makhana_periperi",
  name: "Makhana",
  category_id: "makhana",
  flavor: "Peri Peri",
  title: "Makhana Peri Peri",
  image: "images/makhana_periperi.png",
  description:
   "Spicy, tangy peri peri makhana roasted in small batches for heat seekers.",
  benefits: [
   "Roasted, Not Fried",
   "Light & Crunchy",
   "Fiery Peri Peri",
   "Zero Trans Fat",
   "Perfect Party Snack",
  ],
  benefits_image: "images/makhana_bowl_love.png",
  ingredients: [
   { name: "Makhana", img: "images/ingredient_makhana.png" },
   { name: "Peri Peri Seasoning", img: "images/ingredient_spices.png" },
   { name: "Garlic Powder", img: "images/ingredient_onion.png" },
   { name: "Rock Salt", img: "images/ingredient_salt.png" },
  ],
  specs: {
   Brand: "Rein Oro",
   Flavour: "Peri Peri Spices",
   "Net Weight": "100g, 250g, 500g",
   "Diet Type": "Vegetarian",
   "Shelf Life": "6 Months from date of packaging",
   "Country of Origin": "India",
  },
  nutrition: {
   Calories: "390 Kcal",
   Protein: "9.1g",
   "Total Carbohydrates": "66.8g",
   "Dietary Fiber": "7.2g",
   "Total Fat": "8.2g",
   "Trans Fat": "0g",
   Sodium: "320mg",
  },
  variants: [
   { weight: "100g", mrp: 399, sale_price: 299, stock: 39 },
   { weight: "250g", mrp: 799, sale_price: 599, stock: 28 },
   { weight: "500g", mrp: 1499, sale_price: 1099, stock: 16 },
  ],
 }),
 makeProduct({
  id: "makhana_himalayan",
  name: "Makhana",
  category_id: "makhana",
  flavor: "Himalayan Salt",
  title: "Makhana Himalayan Salt",
  image: "images/makhana_himalayan.png",
  description:
   "Lightly roasted lotus seeds dusted with mineral-rich pink Himalayan rock salt.",
  benefits: [
   "Roasted, Not Fried",
   "Mineral Rich Himalayan Salt",
   "Crunchy & Light",
   "Perfect Daily Snack",
   "Zero Trans Fat",
  ],
  benefits_image: "images/makhana_bowl_love.png",
  ingredients: [
   { name: "Makhana", img: "images/ingredient_makhana.png" },
   { name: "Pink Himalayan Salt", img: "images/ingredient_salt.png" },
   { name: "Cold Pressed Oil", img: "images/ingredient_spices.png" },
  ],
  specs: {
   Brand: "Rein Oro",
   Flavour: "Himalayan Pink Salt",
   "Net Weight": "100g, 250g, 500g",
   "Diet Type": "Vegetarian",
   "Shelf Life": "6 Months from date of packaging",
   "Country of Origin": "India",
  },
  nutrition: {
   Calories: "372 Kcal",
   Protein: "9.6g",
   "Total Carbohydrates": "72.4g",
   "Dietary Fiber": "8.0g",
   "Total Fat": "5.2g",
   "Trans Fat": "0g",
   Sodium: "180mg",
  },
  variants: [
   { weight: "100g", mrp: 349, sale_price: 275, stock: 46 },
   { weight: "250g", mrp: 749, sale_price: 575, stock: 34 },
   { weight: "500g", mrp: 1399, sale_price: 1049, stock: 22 },
  ],
 }),
 makeProduct({
  id: "almonds_california",
  name: "Nuts",
  category_id: "nuts",
  flavor: "Almonds",
  title: "California Premium Almonds",
  image: "images/almonds_california.png",
  description:
   "Hand-selected California almonds, double-sorted for uniform size and premium crunch.",
  benefits: [
   "Double Sorted",
   "High in Vitamin E",
   "Rich in Protein",
   "Premium California Origin",
   "Boosts Brain Health",
  ],
  benefits_image: "images/makhana_bowl_love.png",
  ingredients: [{ name: "Premium Almonds", img: "images/almonds_california.png" }],
  specs: {
   Brand: "Rein Oro",
   Flavour: "Natural Premium Almonds",
   "Net Weight": "250g, 500g",
   "Diet Type": "Vegetarian",
   "Shelf Life": "9 Months from date of packaging",
   "Country of Origin": "USA (California)",
  },
  nutrition: {
   Calories: "579 Kcal",
   Protein: "21.2g",
   "Total Carbohydrates": "21.6g",
   "Dietary Fiber": "12.5g",
   "Total Fat": "49.9g",
   "Trans Fat": "0g",
   Sodium: "1mg",
  },
  variants: [
   { weight: "250g", mrp: 799, sale_price: 649, stock: 31 },
   { weight: "500g", mrp: 1499, sale_price: 1199, stock: 18 },
  ],
  featured: true,
 }),
 makeProduct({
  id: "cashews_roasted",
  name: "Nuts",
  category_id: "nuts",
  flavor: "Roasted & Salted",
  title: "Roasted & Salted Cashews",
  image: "images/cashews_roasted.png",
  description:
   "Creamy cashews roasted to a golden hue and sprinkled with pure sea salt.",
  benefits: [
   "Slow Roasted",
   "Rich & Creamy",
   "Lightly Salted",
   "Healthy Monounsaturated Fats",
   "Handpicked Quality",
  ],
  benefits_image: "images/makhana_bowl_love.png",
  ingredients: [
   { name: "Creamy Cashews", img: "images/cashews_roasted.png" },
   { name: "Rock Salt", img: "images/ingredient_salt.png" },
  ],
  specs: {
   Brand: "Rein Oro",
   Flavour: "Roasted & Salted Cashews",
   "Net Weight": "200g, 500g",
   "Diet Type": "Vegetarian",
   "Shelf Life": "6 Months from date of packaging",
   "Country of Origin": "India",
  },
  nutrition: {
   Calories: "553 Kcal",
   Protein: "18.2g",
   "Total Carbohydrates": "30.2g",
   "Dietary Fiber": "3.3g",
   "Total Fat": "43.8g",
   "Trans Fat": "0g",
   Sodium: "240mg",
  },
  variants: [
   { weight: "200g", mrp: 699, sale_price: 549, stock: 27 },
   { weight: "500g", mrp: 1499, sale_price: 1249, stock: 14 },
  ],
 }),
 makeProduct({
  id: "pistachios_roasted",
  name: "Nuts",
  category_id: "nuts",
  flavor: "Roasted & Salted",
  title: "Pistachios Roasted & Salted",
  image: "images/pistachios_roasted.png",
  description:
   "In-shell premium pistachios, lightly roasted and seasoned with rock salt.",
  benefits: [
   "Easy to Shell",
   "Lightly Roasted",
   "Rich in Antioxidants",
   "Highly Nutritious",
   "100% Natural Processed",
  ],
  benefits_image: "images/makhana_bowl_love.png",
  ingredients: [
   { name: "Premium Pistachios", img: "images/pistachios_roasted.png" },
   { name: "Rock Salt", img: "images/ingredient_salt.png" },
  ],
  specs: {
   Brand: "Rein Oro",
   Flavour: "Roasted & Salted Pistachios",
   "Net Weight": "200g, 500g",
   "Diet Type": "Vegetarian",
   "Shelf Life": "6 Months from date of packaging",
   "Country of Origin": "Iran",
  },
  nutrition: {
   Calories: "562 Kcal",
   Protein: "20.3g",
   "Total Carbohydrates": "27.5g",
   "Dietary Fiber": "10.3g",
   "Total Fat": "45.3g",
   "Trans Fat": "0g",
   Sodium: "290mg",
  },
  variants: [
   { weight: "200g", mrp: 899, sale_price: 699, stock: 25 },
   { weight: "500g", mrp: 1899, sale_price: 1499, stock: 12 },
  ],
 }),
 makeProduct({
  id: "raisins_premium",
  name: "Nuts",
  category_id: "nuts",
  flavor: "Premium Selection",
  title: "Green Raisins Premium Selection",
  image: "images/raisins_premium.png",
  description:
   "Naturally sweet, plump green raisins selected for soft texture and clean sweetness.",
  benefits: [
   "Naturally Sun Dried",
   "Zero Added Sugar",
   "Rich in Iron & Fiber",
   "Sweet & Juicy",
   "Ideal Dessert Topping",
  ],
  benefits_image: "images/makhana_bowl_love.png",
  ingredients: [{ name: "Green Raisins", img: "images/raisins_premium.png" }],
  specs: {
   Brand: "Rein Oro",
   Flavour: "Green Raisins",
   "Net Weight": "250g, 500g",
   "Diet Type": "Vegetarian",
   "Shelf Life": "12 Months from date of packaging",
   "Country of Origin": "India",
  },
  nutrition: {
   Calories: "299 Kcal",
   Protein: "3.1g",
   "Total Carbohydrates": "79.2g",
   "Dietary Fiber": "3.7g",
   "Total Fat": "0.5g",
   "Trans Fat": "0g",
   Sodium: "11mg",
  },
  variants: [
   { weight: "250g", mrp: 449, sale_price: 349, stock: 44 },
   { weight: "500g", mrp: 849, sale_price: 649, stock: 26 },
  ],
 }),
 makeProduct({
  id: "gift_box_premium",
  name: "Gift Box",
  category_id: "gift-box",
  flavor: "Premium Assortment",
  title: "Premium Dry Fruit Gift Box",
  image: "images/gift_box_premium.png",
  description:
   "A curated Rein Oro gift assortment with makhana and premium dry fruits for celebrations and corporate gifting.",
  benefits: [
   "Curated Assortment",
   "Premium Gift Packaging",
   "Ideal for Corporate Gifting",
   "Freshly Packed",
   "Ready to Present",
  ],
  benefits_image: "images/bulk_gifting_hamper.png",
  ingredients: [
   { name: "Makhana", img: "images/ingredient_makhana.png" },
   { name: "Almonds", img: "images/almonds_california.png" },
   { name: "Cashews", img: "images/cashews_roasted.png" },
   { name: "Raisins", img: "images/raisins_premium.png" },
  ],
  specs: {
   Brand: "Rein Oro",
   Flavour: "Premium Assortment",
   "Net Weight": "650g",
   "Diet Type": "Vegetarian",
   "Shelf Life": "6 Months from date of packaging",
   "Country of Origin": "India",
  },
  nutrition: {
   Calories: "Varies by item",
   Protein: "Mixed source",
   "Total Carbohydrates": "Mixed source",
   "Dietary Fiber": "Mixed source",
   "Total Fat": "Mixed source",
   "Trans Fat": "0g",
   Sodium: "Varies by item",
  },
  variants: [
   { weight: "650g", mrp: 1799, sale_price: 1499, stock: 20 },
  ],
  featured: true,
 }),
];

export const defaultCategories = [
 {
  id: "makhana",
  name: "Makhana",
  description: "Slow-roasted premium lotus seeds flavored with exquisite spices.",
  image: "images/makhana_classic.png",
 },
 {
  id: "nuts",
  name: "Premium Nuts",
  description: "Handpicked almonds, cashews, pistachios and raisins.",
  image: "images/almonds_california.png",
 },
 {
  id: "gift-box",
  name: "Gift Box",
  description: "Curated premium assortments for gifting and celebrations.",
  image: "images/gift_box_premium.png",
 },
];
